before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: kittendns
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    hooks:
      post:
        - mkdir -p bin
        - cp {{.Path}} bin/
  - id: plugin_example
    binary: example.so
    dir: plugins/example
    main: example.go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -buildmode=plugin 
    ldflags:
      - -s -w -X main.Version={{.Version}}
    hooks:
      post:
        - mkdir -p bin
        - cp {{.Path}} bin/
  - id: plugin_jsscript
    binary: jsscript.so
    dir: plugins/jsscript
    main: jsscript.go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -buildmode=plugin 
    ldflags:
      - -s -w -X main.Version={{.Version}}
    hooks:
      post:
        - mkdir -p bin
        - cp {{.Path}} bin/
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
release:
  draft: false
  prerelease: false
  github:
    owner: fusion
    name:  kittendns
  header: |
    ## Release {{ .Tag }} on {{ .Date }}
    
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
